### ISSUE TITLE
ADJUSTMENT NEEDED: City needs to be optional from settings. Checkbox_single

### ISSUE THREAD

**Issue by mervb** [mervb/Easy-Property-Listings#173]
http://202.164.55.74/realestatesconnected/wp-admin/admin.php?page=epl-settings

**Comment by mervb** [comment]
Place setting under Location Taxonomy [7                                 ]

Enable City 
City [Label____]

**Comment by mervb** [comment]
Add a label to customise the City label. (City could be town/region etc

![city label](https://cloud.githubusercontent.com/assets/4696393/8562074/45f14d1e-2560-11e5-9306-30bd3aaace89.png)


Move the City option and the Suburb Taxonomy to the Labels setting section

![move settings](https://cloud.githubusercontent.com/assets/4696393/8562072/42cc692a-2560-11e5-8c9b-50e1bb4ddc5b.png)

**Comment by mediatelecom** [comment]
done

**Comment by mervb** [comment]
Still Buggy as per other thread about fatal errors. Adjusting the city/country to off produced fatal errors.

Notice: Undefined index: name in C:\MAMP\htdocs\epl-testing\easypropertylistings\wp-content\plugins\Easy-Property-Listings-1.3-Working\lib\includes\class-property-meta.php on line 37

Fatal error: Cannot access empty property in C:\MAMP\htdocs\epl-testing\easypropertylistings\wp-content\plugins\Easy-Property-Listings-1.3-Working\lib\includes\class-property-meta.php on line 43
